Script improvements

diff --git a/.github/workflows/version_bumper.yaml b/.github/workflows/version_bumper.yaml
--- a/.github/workflows/version_bumper.yaml
+++ b/.github/workflows/version_bumper.yaml
@@ -1,4 +1,4 @@
-name: Check & Bump Version
+name: Version Updater
 on:
   pull_request:
     branches:
@@ -24,7 +24,7 @@ jobs:
         id: is_src_changed
         run: |
           is_changed=`[ "${{ steps.get_stored_hash.outputs.srcHash }}" = "${{ steps.calculate_hash.outputs.hash }}" ] && echo false || echo true`
-          [ $is_changed = true ] && echo "Version update check and bump is required." || echo "Version updated check and bump is not required."
+          [ "$is_changed" = true ] && echo "Version update check and bump is required." || echo "Version updated check and bump is not required."
           echo "::set-output name=changed::is_changed"
   get_current_version:
     name: Get current version
@@ -33,7 +33,7 @@ jobs:
       - check_src_changes
     outputs:
       version: ${{ steps.package-version.outputs.version }}
-    if: ${{ needs.check_src_changes.outputs.is_src_changed }}
+    if: ${{ needs.check_src_changes.outputs.is_src_changed == true }}
     steps:
       - name: Checkout current
         uses: actions/checkout@v2
@@ -47,7 +47,7 @@ jobs:
       - check_src_changes
     outputs:
       version: ${{ steps.package-version.outputs.version }}
-    if: ${{ needs.check_src_changes.outputs.is_src_changed }}
+    if: ${{ needs.check_src_changes.outputs.is_src_changed == true }}
     steps:
       - name: Checkout master
         uses: actions/checkout@v2
@@ -56,23 +56,30 @@ jobs:
       - name: Get master version
         id: package-version
         run: ./.github/scripts/get_package_variable.sh "version"
-  # bump_version_and_hash:
-  #     name: Auto bump version and hash if needed
-  #     runs-on: ubuntu-latest
-  #     env:
-  #       GIT_PUSH_AUTHOR_EMAIL: ${{ secrets.BOT_USER_EMAIL }}
-  #       GIT_PUSH_AUTHOR_NAME: ${{ secrets.BOT_USER_NAME }}
-  #     needs:
-  #       - check_src_changes
-  #       - get_current_version
-  #       - get_master_version
-  #     if: ${{ always() }} && ${{ needs.check_src_changes.outputs.is_src_changed }}
-  #     steps:
-  #       - name: Checkout current
-  #         uses: actions/checkout@v2
-  #       - name: Update hash
-  #         run: ./.github/scripts/set_package_variable.sh "srcHash" ${{ needs.check_src_changes.new_hash }}
-  #       - name: Bump patch version
-  #         run: ./.github/scripts/bump_version.sh "patch"
-  #       - name: Push updated version
-  #         run: ./.github/scripts/git_push.sh "Auto patch version bump"
+  bump_hash_and_version:
+      name: Bump hash and version if needed 
+      runs-on: ubuntu-latest
+      env:
+        GIT_PUSH_AUTHOR_EMAIL: ${{ secrets.BOT_USER_EMAIL }}
+        GIT_PUSH_AUTHOR_NAME: ${{ secrets.BOT_USER_NAME }}
+      needs:
+        - check_src_changes
+        - get_current_version
+        - get_master_version
+      if: ${{ always() && needs.check_src_changes.outputs.is_src_changed == true }}
+      steps:
+        - name: Setup node 12
+          uses: actions/setup-node@v1
+          with:
+            node-version: 12
+        - name: Checkout current
+          uses: actions/checkout@v2
+        - name: Prepare for push
+          run: git checkout "${GITHUB_REF:11}" # PRs are in detached head mode so switch to the PR branch
+        - name: Update hash
+          run: ./.github/scripts/set_package_variable.sh "srcHash" ${{ needs.check_src_changes.new_hash }}
+        - name: Bump patch version if needed
+          if: ${{ needs.get_current_version.outputs.version != needs.get_master_version.outputs.version }}
+          run: ./.github/scripts/bump_version.sh "patch"
+        - name: Push updated package.json
+          run: ./.github/scripts/git_push.sh '`[ ${{ needs.get_current_version.outputs.version }} != ${{ needs.get_master_version.outputs.version }} ] && echo "Updating hash and version" || echo "Updating hash"`'
